# Copyright (C) 2020 QUECTEL Technologies Limited and/or its affiliates("QUECTEL").
# All rights reserved.
#

configure_file (
    "${ql_app_dir}/ql_app_feature_config.h.in"
    "${out_inc_dir}/ql_app_feature_config.h"
)

if (QL_APP_PACK_FILE)
if (QL_CCSDK_BUILD)
set(CONFIG_PACKAGE_FILE_APPIMG_JSON_PATH ${QL_APP_PACK_FILE_JSON_PATH})
else()
set(CONFIG_PACKAGE_FILE_APPIMG_JSON_PATH $ENV{prepack_json_path})
endif()
endif()

if(NOT QL_PROJECT_MIXER AND NOT CONFIG_QUEC_PROJECT_FEATURE_VSIM_ADAPT_STD)
	set(target ${QL_APP_BUILD_VER})
	if(CONFIG_APPIMG_LOAD_FLASH)
		add_appimg_flash_ql_example(${target} ql_init.c)
	endif()
	if(CONFIG_APPIMG_LOAD_FILE)
		add_appimg_file_ql_example(${target} ql_init.c)
	endif()

    if(QL_APP_FEATURE_AUDIO OR QL_APP_FEATURE_PWM_AUDIO)
	    if(QL_APP_FEATURE_AUDIO)
		target_link_libraries(${target} PRIVATE ql_app_audio)
		elseif(QL_APP_FEATURE_PWM_AUDIO)
		target_link_libraries(${target} PRIVATE ql_app_pwm_audio)
		endif()
		if(QL_APP_FEATURE_TTS)
			if(NOT CONFIG_QUEC_PROJECT_FEATURE_TTS_IN_KERNEL)
				add_library(ql_tts_api STATIC IMPORTED)
				set_target_properties(ql_tts_api PROPERTIES IMPORTED_LOCATION ${SOURCE_TOP_DIR}/components/newlib/armca5/libql_api_tts.a)
				target_link_libraries(${target} PRIVATE ql_app_tts ql_tts_api ${libm_file_name})
			else()
			target_link_libraries(${target} PRIVATE ql_app_tts ${libm_file_name})
			endif()
		endif()
	endif()
# if(QL_APP_FEATURE_GNSS)
# 	target_link_libraries(${target} PRIVATE ql_app_gnss)
# endif()
if(QL_APP_FEATURE_HD_GNSS)
	target_link_libraries(${target} PRIVATE ql_app_hd_gnss)
endif()

	target_link_libraries(${target} PRIVATE  ql_app_peripheral)
	# target_link_libraries(${target} PRIVATE  m c)
	# target_link_libraries(${target} PRIVATE sdmmc)
	target_link_libraries(${target} PRIVATE t2n)
	target_link_libraries(${target} PRIVATE rtk)

	target_link_libraries(${target} PRIVATE rs485)
	target_link_libraries(${target} PRIVATE esp32_flash)
	target_link_libraries(${target} PRIVATE modbus_rtu_slave)
	target_link_libraries(${target} PRIVATE uart1_rs485)
	target_link_libraries(${target} PRIVATE usb_acm_netif)

	# target_link_libraries(${target} PRIVATE gnss)
	# target_link_libraries(${target} PRIVATE voice)
	# target_link_libraries(${target} PRIVATE audio)
	# target_link_libraries(${target} PRIVATE lis3dsh)
	target_link_libraries(${target} PRIVATE ec600u_bl0939)
	# target_link_libraries(${target} PRIVATE lvgl_lib)
	# target_link_libraries(${target} PRIVATE lvgl_app)
	# target_include_directories(${target} PUBLIC audio/pwm_audio/inc)
	target_link_libraries(${target} PRIVATE esp32_network)
	target_link_libraries(${target} PRIVATE mqtt_test)

relative_glob(srcs *.h *.c )
beautify_c_code(${target} ${srcs})
endif()
